CREATE TABLE IF NOT EXISTS "user"
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_type         VARCHAR(31),
    first_name        VARCHAR(255)                            NOT NULL,
    last_name         VARCHAR(255)                            NOT NULL,
    birth_date        VARCHAR(255)                            NOT NULL,
    gender            VARCHAR(255)                            NOT NULL,
    email             VARCHAR(255)                            NOT NULL,
    phone_number      VARCHAR(255)                            NOT NULL,
    address           VARCHAR(255)                            NOT NULL,
    username          VARCHAR(255)                            NOT NULL,
    password          VARCHAR(255),
    salt_password     VARCHAR(255),
    verification_code VARCHAR(255),
    position          VARCHAR(255) DEFAULT 'N/A'              NOT NULL,
    department        VARCHAR(255) DEFAULT 'N/A'              NOT NULL,
    active            BOOLEAN      DEFAULT true               NOT NULL,
    is_admin          BOOLEAN      DEFAULT false              NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

alter table "user"
    owner to user_service_user;

CREATE TABLE IF NOT EXISTS user_permissions
(
    user_id    BIGINT NOT NULL,
    permission VARCHAR(255)
);

alter table user_permissions
    owner to user_service_user;

ALTER TABLE "user"
    DROP CONSTRAINT IF EXISTS uc_user_email;

ALTER TABLE "user"
    DROP CONSTRAINT IF EXISTS uc_user_username;


ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE user_permissions
    DROP CONSTRAINT IF EXISTS fk_user_permissions_on_customer;

ALTER TABLE user_permissions
    ADD CONSTRAINT fk_user_permissions_on_customer FOREIGN KEY (user_id) REFERENCES "user" (id);


create table if not exists reset_password
(
    type            integer      not null,
    used            boolean      not null,
    created_date    bigint       not null,
    expiration_date bigint       not null,
    id              bigint generated by default as identity
        primary key,
    user_id         bigint,
    token           varchar(255) not null
);

alter table reset_password
    owner to user_service_user;

create table if not exists set_password
(
    customer        boolean,
    used            boolean,
    created_date    timestamp(6) with time zone,
    expiration_date timestamp(6) with time zone,
    id              bigint generated by default as identity
        primary key,
    user_id         bigint,
    token           varchar(255)
);

alter table set_password
    owner to user_service_user;

